<?php

/**
 * @file
 * Primary module hooks for tommasocc Layout Builder module.
 */
use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function tommasocc_layout_builder_theme($existing, $type, $theme, $path) {
  return [
    'block__inline_block' => [
      'base hook' => 'block',
    ]
  ];
};

/**
 * Implements hook_preprocess_HOOK().
 */
function tommasocc_layout_builder_preprocess_block(&$variables) {
  $base_plugin_id = $variables['elements']['#base_plugin_id'] ?: NULL;
  $custom_block_id = $variables['elements']['#derivative_plugin_id'];
  if ($base_plugin_id == 'inline_block') {
    $custom_block_id = $variables['elements']['#derivative_plugin_id'];
    $variables['attributes']['class'][] = 'c-block--' . $custom_block_id;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function tommasocc_layout_builder_preprocess_layout(&$variables) {
  $entity = $variables['layout'];

  $variables['attributes']['class'][] = Html::cleanCssIdentifier(
    str_replace($entity->get('provider') . '_', 'layout--', $entity->id()),
  );
}
